name       : go-ipfs
version    : 0.11.0
release    : 10
source     :
    - https://github.com/ipfs/go-ipfs/releases/download/v0.11.0/go-ipfs-source.tar.gz : 9533c69c5a8383231699208f98b1e0b863672503168bd2cface65f0e0792f58e
license    : MIT
component  : network.util
networking : yes
summary    : A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
description: |
    IPFS (the InterPlanetary File System) is a new hypermedia distribution protocol, addressed by content and identities. IPFS enables the creation of completely distributed applications. It aims to make the web faster, safer, and more open.

    IPFS is a distributed file system that seeks to connect all computing devices with the same system of files. In some ways, this is similar to the original aims of the Web, but IPFS is actually more similar to a single bittorrent swarm exchanging git objects.
builddeps  :
    - git
    - golang
build      : |
    %make build
    ./cmd/ipfs/ipfs commands completion bash > ipfs-completion.bash
install    : |
    install -D -m 00755 cmd/ipfs/ipfs $installdir/usr/bin/ipfs
    install -D -m 00644 $pkgfiles/systemd/* -t $installdir/usr/lib/systemd/user/
    install -D -m 00644 ipfs-completion.bash $installdir/usr/share/bash-completion/completions/ipfs
