name       : go-ipfs
version    : 0.4.23
release    : 2
source     :
    - https://dist.ipfs.io/go-ipfs/v0.4.23/go-ipfs-source.tar.gz : aa445825f0658d3494460d571b41b81eff4f8544d2a5ce9765dd1c6620c931a4
license    : MIT
component  : network.util
networking : yes
summary    : A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
description: "IPFS (the InterPlanetary File System) is a new hypermedia distribution protocol, addressed by content and identities. IPFS enables the creation of completely distributed applications. It aims\
    \ to make the web faster, safer, and more open.\n\nIPFS is a distributed file system that seeks to connect all computing devices with the same system of files. In some ways, this is similar to the original\
    \ aims of the Web, but IPFS is actually more similar to a single bittorrent swarm exchanging git objects. \n"
builddeps  :
    - git
    - golang
build      : |
    %make build
install    : |
    install -D -m 00755 cmd/ipfs/ipfs $installdir/usr/bin/ipfs
    install -D -m 00644 $pkgfiles/systemd/* -t $installdir/usr/lib/systemd/user/
    install -D -m 00644 misc/completion/ipfs-completion.bash $installdir/usr/share/bash-completions/completions/ipfs
