name       : go-ipfs
version    : 0.6.0
release    : 3
source     :
    - https://dist.ipfs.io/go-ipfs/v0.6.0/go-ipfs-source.tar.gz : 00d96f0983dea0170bf61351a0a0ab39f1515b919a0a7ff5055eca25a4c06f91
license    : MIT
component  : network.util
networking : yes
summary    : A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
description: |
    IPFS (the InterPlanetary File System) is a new hypermedia distribution protocol, addressed by content and identities. IPFS enables the creation of completely distributed applications. It aims to make the web faster, safer, and more open.

    IPFS is a distributed file system that seeks to connect all computing devices with the same system of files. In some ways, this is similar to the original aims of the Web, but IPFS is actually more similar to a single bittorrent swarm exchanging git objects.
builddeps  :
    - git
    - golang
build      : |
    %make build
install    : |
    install -D -m 00755 cmd/ipfs/ipfs $installdir/usr/bin/ipfs
    install -D -m 00644 $pkgfiles/systemd/* -t $installdir/usr/lib/systemd/user/
    install -D -m 00644 misc/completion/ipfs-completion.bash $installdir/usr/share/bash-completions/completions/ipfs
