name       : go-ipfs
version    : 0.12.2
release    : 13
source     :
    - https://github.com/ipfs/go-ipfs/releases/download/v0.12.2/go-ipfs-source.tar.gz : eba34d2cc49f7811d087f4259c44c1fecb2b6bd08a6c3fa3b5a26e5fed78c74d
license    : MIT
component  : network.util
networking : yes
summary    : A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
description: |
    IPFS (the InterPlanetary File System) is a new hypermedia distribution protocol, addressed by content and identities. IPFS enables the creation of completely distributed applications. It aims to make the web faster, safer, and more open.

    IPFS is a distributed file system that seeks to connect all computing devices with the same system of files. In some ways, this is similar to the original aims of the Web, but IPFS is actually more similar to a single bittorrent swarm exchanging git objects.
builddeps  :
    - git
    - golang
build      : |
    %make build
    ./cmd/ipfs/ipfs commands completion bash > ipfs-completion.bash
install    : |
    install -Dm00755 cmd/ipfs/ipfs $installdir/usr/bin/ipfs
    install -Dm00644 $pkgfiles/systemd/* -t $installdir/usr/lib/systemd/user/
    install -Dm00644 ipfs-completion.bash $installdir/usr/share/bash-completion/completions/ipfs
